export enum ErrorCodes {
  ERROR_INESPERADO = 'ERROR_INESPERADO',
  DATOS_INVALIDOS = 'DATOS_INVALIDOS',

  CORREO_REGISTRADO = 'CORREO_REGISTRADO',
  CREDENCIALES_INVALIDAS = 'CREDENCIALES_INVALIDAS',
  ERROR_REGISTRO = 'ERROR_REGISTRO',
  ROL_REQUERIDO = 'ROL_REQUERIDO',
  COMPORTAMIENTO_SOSPECHOSO = 'COMPORTAMIENTO_SOSPECHOSO',

  SUBASTA_NO_ENCONTRADA = 'SUBASTA_NO_ENCONTRADA',
  SUBASTA_NO_PROPIA = 'SUBASTA_NO_PROPIA',
  SUBASTA_NO_EDITABLE = 'SUBASTA_NO_EDITABLE',
  SUBASTA_NO_ELIMINABLE = 'SUBASTA_NO_ELIMINABLE',
  SUBASTA_PRIVADA = 'SUBASTA_PRIVADA',
  ESTADO_INVALIDO = 'ESTADO_INVALIDO',
  MOTIVO_REQUERIDO = 'MOTIVO_RECHAZO_MOTIVO',
  FECHAS_INVALIDAS = 'FECHAS_INVALIDAS',
  CATEGORIA_NO_ENCONTRADA = 'CATEGORIA_NO_ENCONTRADA',

  IMAGEN_INVALIDA = 'IMAGEN_INVALIDA',
  IMAGEN_MUY_GRANDE = 'IMAGEN_MUY_GRANDE',
  IMAGEN_NO_ACCESIBLE = 'IMAGEN_NO_ACCESIBLE',
  IMAGEN_REQUERIDA = 'IMAGEN_REQUERIDA',
  IMAGEN_MODERACION_RECHAZADA = 'IMAGEN_MODERACION_RECHAZADA',
  MODERACION_NO_DISPONIBLE = 'MODERACION_NO_DISPONIBLE',
  IMAGEN_NO_MODERABLE = 'IMAGEN_NO_MODERABLE',
  ERROR_SUBIDA = 'ERROR_SUBIDA',

  PUJA_INVALIDA = 'PUJA_INVALIDA',
  SUBASTA_CERRADA = 'SUBASTA_CERRADA',
  SUBASTA_NO_INICIADA = 'SUBASTA_NO_INICIADA',
  PUJA_PROPIA_SUBASTA = 'PUJA_PROPIA_SUBASTA',

  PAGO_NO_ENCONTRADO = 'PAGO_NO_ENCONTRADO',
  PAGO_NO_PROPIO = 'PAGO_NO_PROPIO',
  PAGO_YA_PROCESADO = 'PAGO_YA_PROCESADO',
  PAGO_VENCIDO = 'PAGO_VENCIDO',
  DATOS_TARJETA_INVALIDOS = 'DATOS_TARJETA_INVALIDOS',

  YA_INSCRITO = 'YA_INSCRITO',
  NO_INSCRITO = 'NO_INSCRITO',
  SALA_LLENA = 'SALA_LLENA',

  YA_CALIFICADO = 'YA_CALIFICADO',
  NO_GANADOR = 'NO_GANADOR',

  RESERVA_NO_ENCONTRADA = 'RESERVA_NO_ENCONTRADA',
  RESERVA_YA_RESPONDIDA = 'RESERVA_YA_RESPONDIDA',
  RESERVA_REQUERIDA = 'RESERVA_REQUERIDA',
  USUARIO_NO_ENCONTRADO = 'USUARIO_NO_ENCONTRADO',
}
